function [Phonemes] = add_Phonation_to_Phonemes(Phonemes)

% Read Phonemes and add the following details to each Phoneme:
% PHONEMIC STATUS	PHONATION	PLACE	MANNER	EXAMPLE
%
% EG
% SEGMENT	PHONEMIC    PHONATION	PLACE   MANNER	EXAMPLE
% p         C           VL          LAB     PLO     pet
% t         C           VL          ALV     PLO     tap
% k         C           VL          VEL     PLO     cap


%%    
    
    
currentTable ={'p','C','VL','LAB','PLO';... 
't','C','VL','ALV','PLO';... 
'k','C','VL','VEL','PLO';... 
'b','C','V','LAB','PLO';... 
'd','C','V','ALV','PLO';... 
'g','C','V','VEL','PLO';... 
'm','C','V','LAB','NAS';... 
'n','C','V','ALV','NAS';... 
'ng','C','V','VEL','NAS';... 
'f','C','VL','LABD','FRIC';... 
's','C','VL','ALV','FRIC';... 
'th','C','VL','DENT','FRIC';... 
'sh','C','VL','PALV','FRIC';... 
'v','C','V','LABD','FRIC';... 
'dh','C','V','DENT','FRIC';... 
'z','C','V','ALV','FRIC';... 
'zh','C','V','PALV','FRIC';... 
'h','C','VL','GLOT','FRIC';... 
'ch','C','VL','PALV','AFF';... 
'jh','C','V','PALV','AFF';... 
'l','C','V','ALV','LAPP';... 
'r','C','V','ALV','APPR';... 
'w','C','V','LABV','APPR';... 
'y','C','V','PAL','APPR';... 
'i','V','V','FRO','CLO';... 
'uh','V','V','MID','OPN';... 
'aa','V','V','BAC','OPN';... 
'ai','D','V','NS','NS';... 
'ou','D','V','NS','NS';... 
'e','V','V','FRO','HOP';... 
'u','V','V','BAC','CLO';... 
'oo','V','V','BAC','HCL';... 
'ei','D','V','NS','NS';... 
'i@','D','V','NS','NS';... 
'a','V','V','FRO','OPN';... 
'@','V','V','MID','HOP';... 
'uu','V','V','BAC','CLO';... 
'oi','D','V','NS','NS';... 
'e@','D','V','NS','NS';... 
'o','V','V','BAC','HOP';... 
'ii','V','V','FRO','CLO';... 
'@@','D','V','NS','NS';... 
'au','D','V','NS','NS';... 
'u@','D','V','NS','NS'};
%%
% Read the Phonemes
numPhonemes             = size(Phonemes,1);

for k=1:numPhonemes
    % Each line is a {start end phoneme}
    placeTable = find(strcmp(currentTable,Phonemes{k,3}));
    if ~isempty(placeTable)
        Phonemes{k,4} =     currentTable{placeTable,2};
        Phonemes{k,5} =     currentTable{placeTable,3};
        Phonemes{k,6} =     currentTable{placeTable,4};
        Phonemes{k,7} =     currentTable{placeTable,5};
    else
        % Add option to display a phoneme not on the table
        if ~strcmp(Phonemes{k,3},'sil')
            if ~strcmp(Phonemes{k,3},'breath')
                disp(Phonemes{k,3})
            end
        end
    end
end
    
    
    
end
